apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  labels:
    app: inference-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
    spec:
      nodeSelector:
        workload: general
      containers:
        - name: api
          image: inference-runtime:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: ENABLE_REDIS_CACHE
              value: "false"
            - name: ENABLE_ASYNC_QUEUE
              value: "true"
            - name: INFERENCE_DEVICE
              value: "cpu"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: MODEL_V1_NAME
              value: "distilbert-base-uncased-finetuned-sst-2-english"
            - name: MODEL_V2_NAME
              value: "cardiffnlp/twitter-roberta-base-sentiment-latest"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
