apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker
  labels:
    app: ai-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-worker
  template:
    metadata:
      labels:
        app: ai-worker
    spec:
      nodeSelector:
        workload: general
      containers:
        - name: worker
          image: ai-inference-platform:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "worker.py"]
          env:
            - name: ENABLE_REDIS_CACHE
              value: "false"
            - name: ENABLE_ASYNC_QUEUE
              value: "true"
            - name: INFERENCE_DEVICE
              value: "cpu"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: MODEL_V1_NAME
              value: "distilbert-base-uncased-finetuned-sst-2-english"
            - name: MODEL_V2_NAME
              value: "cardiffnlp/twitter-roberta-base-sentiment-latest"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
